#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSystem.SalaryManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KangKeDe")]
	public partial class SalaryManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertK_Salary_Management(K_Salary_Management instance);
    partial void UpdateK_Salary_Management(K_Salary_Management instance);
    partial void DeleteK_Salary_Management(K_Salary_Management instance);
    #endregion
		
		public SalaryManagementDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["testConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SalaryManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SalaryManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SalaryManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SalaryManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<K_Salary_Management> K_Salary_Management
		{
			get
			{
				return this.GetTable<K_Salary_Management>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.K_Salary_Management")]
	public partial class K_Salary_Management : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sm_id;
		
		private string _sm_project;
		
		private System.Nullable<int> _sm_serial_number;
		
		private System.Nullable<bool> _sm_use;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsm_idChanging(int value);
    partial void Onsm_idChanged();
    partial void Onsm_projectChanging(string value);
    partial void Onsm_projectChanged();
    partial void Onsm_serial_numberChanging(System.Nullable<int> value);
    partial void Onsm_serial_numberChanged();
    partial void Onsm_useChanging(System.Nullable<bool> value);
    partial void Onsm_useChanged();
    #endregion
		
		public K_Salary_Management()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sm_id
		{
			get
			{
				return this._sm_id;
			}
			set
			{
				if ((this._sm_id != value))
				{
					this.Onsm_idChanging(value);
					this.SendPropertyChanging();
					this._sm_id = value;
					this.SendPropertyChanged("sm_id");
					this.Onsm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_project", DbType="VarChar(20)")]
		public string sm_project
		{
			get
			{
				return this._sm_project;
			}
			set
			{
				if ((this._sm_project != value))
				{
					this.Onsm_projectChanging(value);
					this.SendPropertyChanging();
					this._sm_project = value;
					this.SendPropertyChanged("sm_project");
					this.Onsm_projectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_serial_number", DbType="Int")]
		public System.Nullable<int> sm_serial_number
		{
			get
			{
				return this._sm_serial_number;
			}
			set
			{
				if ((this._sm_serial_number != value))
				{
					this.Onsm_serial_numberChanging(value);
					this.SendPropertyChanging();
					this._sm_serial_number = value;
					this.SendPropertyChanged("sm_serial_number");
					this.Onsm_serial_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sm_use", DbType="Bit")]
		public System.Nullable<bool> sm_use
		{
			get
			{
				return this._sm_use;
			}
			set
			{
				if ((this._sm_use != value))
				{
					this.Onsm_useChanging(value);
					this.SendPropertyChanging();
					this._sm_use = value;
					this.SendPropertyChanged("sm_use");
					this.Onsm_useChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
